version: "3.9"

services:
  database:
    image: postgres
    container_name: fin_api
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

  app:
      build: .
      container_name: ignite_api
      restart: always
      ports:
        - 3332:3332
        - 9230:9230
      volumes:
        - .:/usr/app
      links:
        - database
      depends_on:
        - database

volumes:
  pgdata:
    driver: local
